baseURL = "https://odahub.io/"
languageCode = "en-us"
title = "About ODA"
theme = ["hugo-notice", "hugo-book"]
#theme = "hugo-paper"

relativeURLs = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        enableDefault = true