name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get install -y build-essential hugo      

    - name: Configure git
      run: |
        git config --global user.email "bot@odahub.io"
        git config --global user.name "ODA Bot"

    - name: Prepare Ontology
      run: make -B ontology

    - name: Compile Ontology
      run: make -B ontology-web

    - name: Compile Hugo Site
      run: |
        hugo
        cp public/ontology/index-en.html public/ontology/index.html
        rm -rfv oda-hub.github.io

    - name: Publish Site
      if: ! github.event.pull_request
      env:
        PUSH_SECRET: ${{ secrets.PUSH_SECRET }} 
      run: |
        git clone https://mmoda-bot:$PUSH_SECRET@github.com/oda-hub/oda-hub.github.io/
        rsync -av public/ oda-hub.github.io/
        cd oda-hub.github.io/
        git add *
        git commit -a -m "update"
        git push
  