name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get install -y build-essential hugo      

    - name: Configure git
      run: |
        git config --global user.email "bot@odahub.io"
        git config --global user.name "ODA Bot"

    - name: Prepare Ontology
      run: make -B ontology

    - name: Compile Ontology
      run: make -B ontology-web

    - name: Compile Site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: make publish
